import com.vanniktech.maven.publish.SonatypeHost

plugins {
	id 'java-library'
	id 'org.springframework.boot' version '3.5.7'
	id 'io.spring.dependency-management' version '1.1.7'
	id "com.vanniktech.maven.publish" version "0.32.0"
	id 'signing'
}

group = 'com.soyesenna'
version = '0.1.0'
description = 'JWT Toolkit for Spring Project'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

repositories {
	mavenCentral()
}

tasks.withType(Javadoc) {
	options {
		encoding 'UTF-8'
	}
}

signing {
	sign publishing.publications
}

mavenPublishing {
	signAllPublications()
	publishToMavenCentral(SonatypeHost.CENTRAL_PORTAL)

	coordinates("com.soyesenna", "spring-jwt-toolkit", "0.1.0")

	pom {
		name = 'spring-jwt-toolkit'
		description = 'JWT Toolkit for Spring Project'
		url = 'https://github.com/soyesenna/spring-jwt-toolkit.git'

		licenses {
			license {
				name = 'Apache License'
				url = 'https://github.com/soyesenna/spring-jwt-toolkit/blob/main/LICENSE'
			}
		}

		developers {
			developer {
				id = 'soyesenna'
				name = 'Jooyoung Kim'
				email = 'kjy915875@gmail.com'
			}
		}

		scm {
			connection = 'scm:git:github.com/soyesenna/spring-jwt-toolkit.git'
			developerConnection = 'scm:git:ssh://github.com:soyesenna/spring-jwt-toolkit.git'
			url = 'https://github.com/soyesenna/spring-jwt-toolkit/tree/main'
		}
	}
}

dependencies {
	// spring
	api 'org.springframework.boot:spring-boot-starter'
	api 'org.springframework.security:spring-security-core'
	api 'org.springframework:spring-web'
	compileOnly 'jakarta.servlet:jakarta.servlet-api:6.0.0'
	testImplementation 'jakarta.servlet:jakarta.servlet-api:6.0.0'

	// lombok
	compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'

	// jwt
	api 'io.jsonwebtoken:jjwt-api:0.12.3'
	api 'io.jsonwebtoken:jjwt-impl:0.12.3'
	api 'io.jsonwebtoken:jjwt-jackson:0.12.3'

	// jackson
	api 'com.fasterxml.jackson.core:jackson-databind'
	api 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310'

	// test
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
	useJUnitPlatform()
}
